### ISSUE TITLE
Obsidian Imports Are In Reverse Timestamp Order

### ISSUE THREAD

**Issue by dionvansevenant** [tech-reclipped/ReClipped-Obsidian-Official#1]
I just signed up and am testing creating notes via the Chrome plugin and then syncing with Obsidian using the Obsidian plugin.

In the Reclipped web interface, everything is in chronological order, from the beginning of the video to the end.

Chrome Plugin:
![chrome_IwZXLP1KDH](https://github.com/tech-reclipped/ReClipped-Obsidian-Official/assets/66170704/36b52693-88da-48b4-b3a4-f98159209553)

Reclipped Web:
![chrome_iBMh825dfp](https://github.com/tech-reclipped/ReClipped-Obsidian-Official/assets/66170704/93dcb99d-867b-474c-a67f-839a3c064cc0)

However, once the video notes are synced to Obsidian, they are in *reverse* chronological order:
![Obsidian_siw8sz3hxW](https://github.com/tech-reclipped/ReClipped-Obsidian-Official/assets/66170704/c1968826-aeca-43a7-ba3e-551ab8a982c6)

I don't see a setting anywhere to change this.

Am I missing something?

If not, this feels like a bug.

**Comment by tech-reclipped** [comment]
@dionvansevenant thank you for raising this issue, we have fixed this issue, 
you can use the hotkey: Delete and reimport this document (we prefer Ctrl+R) for single document reload or you may delete the created folders and re-sync again.

**Comment by dionvansevenant** [comment]
Wow! Fast response! Thank you!

I was off for a couple of days, so was only able to check it today.

Delete and re-sync worked and the timestamps are in ascending chronological
order in Obsidian now.

Thank you!

-- Dion
