### ISSUE TITLE
Feature Request: Preserve Chinese Characters in Exported Note Titles

### ISSUE THREAD

**Issue by fornewfork** [tech-reclipped/ReClipped-Obsidian-Official#6]
## Issue Description
Currently, when exporting notes from YouTube videos with Chinese titles, the plugin converts Chinese characters to pinyin. This reduces readability and searchability. For example:

Video title: "5分钟讲解机器学习中的信息熵, 相对熵与交叉熵 - Knowledge Capsules 001"
(https://www.youtube.com/watch?v=dQP4QXbR0RQ)

Current exported note title:
"5fen-zhong-jiang-jie-ji-qi-xue-xi-zhong-de-xin-xi-shang-xiang-dui-shang-yu-jiao-cha-shang-knowledge-capsules-001"

Desired note title:
"5分钟讲解机器学习中的信息熵, 相对熵与交叉熵 - Knowledge Capsules 001"

## Rationale
1. Improve readability for Chinese users
2. Facilitate note management and searching within Obsidian
3. Maintain consistency with original video titles

Thank you for your consideration!

**Comment by tech-reclipped** [comment]
@fornewfork this has been taken care of from the backend, please check this should work fine now, and we can close this issue after confirmation.

**Comment by fornewfork** [comment]
I had checked it and it works fine now, thanks!
